import type { Metadata } from "next";
import localFont from "next/font/local";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const montserratFont =  Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: [ "100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 200 300 900",
});

export const metadata: Metadata = {
  title: "Crud Blog",
  description: "Generated by create next app",
  authors: [{ name: "Zahida Abbasi" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap"
        />
      </head>
      <body
        className={`${montserratFont.variable} ${geistMono.variable} antialiased`}
        style={{ fontFamily: "Montserrat, sans-serif" }}
      >
        <div className="max-w-3xl mx-auto">
        <header className="p-6 border-b flex justify-between items-center bg-slate-500 text-white rounded-b-lg rounded-br-lg">
            <Link href={"/"} className="font-bold md:text-3xl">Tech Blog</Link>
            <Link href={"/create"} className="font-bold border-2 p-3 px-4 text-sm rounded-full grid place-items-center shadow-black shadow-md">Add New</Link>
        </header>
         <main className="p-4 text-lg">{children}</main>
         <footer></footer>
        </div>
      </body>
    </html>
  );
}
